#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=Test-run
#SBATCH --ntasks=1
#SBATCH --time=15:00:00
#SBATCH --output=outfiles/hiql-visual-cube-single-play_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate myenv

cd ~/ogbench/impls/

# Install critical dependencies directly with pip
# echo "Installing dependencies..."
# pip install -r requirements.txt

export WANDB_API_KEY=

export MUJOCO_GL=egl

python main.py --env_name=visual-cube-single-play-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/hiql.py --agent.batch_size=256 --agent.encoder=impala_small --agent.high_alpha=3.0 --agent.low_actor_rep_grad=True --agent.low_alpha=3.0 --agent.p_aug=0.5 --agent.subgoal_steps=10